### ISSUE TITLE
Handle multi-line code snippets correctly

### ISSUE THREAD

**Issue by pranavgaikwad** [konveyor/tackle2-addon-analyzer#24]
It appears that whenever we have multi-line code snippet strings in the analyzer output, the addon fails to post the analysis. I could be totally wrong on this one, I just observed this happening after my change in the analyzer that generate multi-line code snips like below:

```yaml
    filecontent-codesnip-test:
      description: ""
      category: potential
      incidents:
      - uri: file:///analyzer-lsp/examples/customers-tomcat-legacy/Dockerfile
        message: Found usage of openjdk base image
        codeSnip: |
          1  ########################################
          2  # Build Image
          3  ########################################
          4  # FROM maven:3.6-jdk-8-slim as build 
          5  FROM maven:3.8-openjdk-11 as build
        lineNumber: 5
        variables:
          matchingText: FROM maven:3.8-openjdk-11 as build
```
