### ISSUE TITLE
Analyzer ruleset errors not reported correctly.

### ISSUE THREAD

**Issue by jortel** [konveyor/tackle2-addon-analyzer#26]
Analyzer ruleset errors not reported correctly.
Should be reported as Report.Errors and Report.Status == Failed.
Errors reported as map keyed by ruleid which needs to be propagated. 
```
report:
    id: 25
    createuser: admin.noauth
    updateuser: admin.noauth
    createtime: 2023-07-14T12:40:44.131234629Z
    status: Failed
    errors:
        - severity: Error
          description: '[Analyzer] eap8/eap7.eap8-faces-00009: Malformed response from grep, cannot parse  with pattern {filepath}:{lineNumber}:{matchingText}'
    activity:
        - Fetching application.
```

Depends on: https://github.com/konveyor/tackle2-hub/pull/441

closes: #26

---

Also, prevent downloading duplicate rulesets.

closes: #11
