### ISSUE TITLE
[Bug] Binary analysis fails for tackle-testapp

### ISSUE THREAD

**Issue by mguetta1** [konveyor/tackle2-addon-analyzer#71]
### Konveyor version
0.3.0-rc.3

### Current Behavior
Binary analysis fails

### Analysis details
```
id: 2
createTime: 2023-12-28T12:36:50.708566999Z
name: app1-bin2.2.windup
addon: analyzer
data:
    mode:
        artifact: ""
        binary: true
        withDeps: false
    rules:
        labels:
            excluded: []
            included:
                - konveyor.io/target=cloud-readiness
        path: ""
        tags:
            excluded: []
    scope:
        packages:
            excluded: []
            included: []
        withKnownLibs: false
    sources: []
    tagger:
        enabled: true
    targets: []
    verbosity: 0
application:
    id: 2
    name: app1-bin2
state: Failed
image: quay.io/konveyor/tackle2-addon-analyzer@sha256:72cfb9e945fd634abddb6c70b3dae57e96af9224e4e8796ab9e48cea6994d014
pod: konveyor-tackle/task-2-kjgqz
started: 2023-12-28T12:36:51.239658406Z
terminated: 2023-12-28T12:36:56.420449135Z
bucket:
    id: 4
    name: ""
errors:
    - severity: Error
      description: exit status 1
    - severity: Error
      description: 'Pod failed: Error'
activity:
    - Fetching application.
    - '[CMD] Running: /usr/bin/ssh-agent -a /tmp/agent.1'
    - '[CMD] /usr/bin/ssh-agent succeeded.'
    - '[SSH] Agent started.'
    - '[MVN] Using credentials (id=3) shveta22.'
    - '[FILE] Created /addon/settings.xml.'
    - '[MVN] Using settings file(path=/addon/settings.xml).'
    - '[MVN] Fetch artifact io.konveyor.demo:customers-tomcat:0.0.1-SNAPSHOT:war.'
    - '[CMD] Running: /usr/bin/svn dependency:copy -Dartifact=io.konveyor.demo:customers-tomcat:0.0.1-SNAPSHOT:war -Dmdep.useBaseVersion=true -DoutputDirectory=/addon/bin/maven -Dmaven.repo.local=/cache/m2 -s /addon/settings.xml'
    - '[CMD] /usr/bin/svn failed: exit status 1'
attached:
    - id: 346
      name: ssh-agent.output
      activity: 2
    - id: 347
      name: svn.output
      activity: 9
```

### How Reproducible
Always

### Steps To Reproduce
Analyze tackle-test app with the configuration available in the Environment section.

### Environment
```
- Konveyor 0.3.0-rc.3
- Binary source application: io.konveyor.demo:customers-tomcat:0.0.1-SNAPSHOT:war
- Analysis configuration:
  - Binary
  - cloud-readiness
  - Application and internal dependencies only
  - No custom rules
  - No additional advanced options
```

### Anything else?
The issue is not reproducible using downstream build: mta-operator-bundle-container-7.0.0-48
