### ISSUE TITLE
:sparkles: support multiple providers in the addon workflow

### ISSUE THREAD

**Issue by jortel** [konveyor/tackle2-addon-analyzer#83]
Support multiple providers.

Requires: https://github.com/konveyor/tackle2-hub/issues/599

#### Resource Injector ####

Aggregate the initConfig fragments from each Extension.metadata.

Inject information into the initConfig.
- credentials.

Considering: To support this, a set of injectors will be provided to get, store hub REST resource (fields). Fetched resources are assigned to variables that may be used in the metadata.
Resource:
- selector (format: \<kind>:\<key>=\<value>)
- fields[]:
  - name: - name.
  - path: - (optional) value stored at the specified path.
  - key:  - value stored in key referenced as $(_key_). Assigned to path, when specified.

Example:
```
metadata:
  resources:
  - kind: identity:kind=maven
    fields:
    - name: settings
      path: /shared/creds/maven/settings.xml
       key: settings.path
  - kind: identity=other
    fields:
    - name: user
       key: auth.user
    - name: password
       key: auth.password
  provider:
    initConfig:
     mavenSettingsPath: $(settings.path)
     user: $(auth.user)
     password: $(auth.password)
```
